# Generated by Django 4.1.5 on 2023-02-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('distance', models.IntegerField()),
                ('nights', models.IntegerField()),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=250)),
            ],
        ),
    ]
