# Generated by Django 4.1.5 on 2023-02-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_trip_added_gear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='added_gear',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='trip',
        ),
        migrations.AddField(
            model_name='gear',
            name='trip',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gears', to='main.trip'),
        ),
    ]
