# Generated by Django 4.1.5 on 2023-02-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_trip_gear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='gear',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
