# Generated by Django 4.1.5 on 2023-02-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_trip_gear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='gear',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='trip',
        ),
        migrations.AddField(
            model_name='gear',
            name='trip',
            field=models.ManyToManyField(to='main.trip'),
        ),
    ]
