# Generated by Django 4.1.5 on 2023-02-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_gear_trip_gear_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='trip',
        ),
    ]
