# Generated by Django 4.1.5 on 2023-02-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_gear_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='gear',
            field=models.ManyToManyField(to='main.gear'),
        ),
    ]
